# Exercício de Programação 5

<font color="red">**Prazo de submissão: 23:55 do dia 23.08.2021** </font>

2021.1 Álgebra Linear Computacional - DCC - UFMG

Erickson - Fabricio

Instruções:
* Antes de submeter suas soluções, certifique-se de que tudo roda como esperado. Primeiro, **reinicie o kernel** no menu, selecione Kernel $\rightarrow$ Restart e então execute **todas as células** (no menu, Cell $\rightarrow$ Run All)
* Apenas o arquivo .ipynb deve ser submetido. Ele não deve ser compactado.
* Não deixe de preencher seu nome e número de matrícula na célula a seguir

**Nome do aluno:** Flávio Marcilio de Oliveira

## Introdução
Esse EP será dividido em 2 partes:

1. Métodos iterativos para calcular autovalores e singular values.
3. Métodos iterativos para solução de sistemas $Ax = b$ (Jacob e Seidel)

Os conceitos cobrados aqui são discutidos nas aulas que abrangem o conteúdo de cada parte e elas devem ser a principal fonte de consulta para suas soluções.

In [1]:
import matplotlib.pyplot as plt
import numpy as np

### Questão 1 - Cálculo de autovalores e valores singulares


Nessa primeira parte, vamos implementar o algoritmo QR para obtenção dos autovalores de uma matriz A, como foi descrito nas aulas.

Abaixo temos a matriz A:

In [2]:
# ATENÇÃO: Não editar esta célula
A = np.vander(np.array([5, 4, 3, 2, 1]))
print(A)

[[625 125  25   5   1]
 [256  64  16   4   1]
 [ 81  27   9   3   1]
 [ 16   8   4   2   1]
 [  1   1   1   1   1]]


**1.1.1** Implemente o algoritmo QR, utilizando um **while loop** até satisfazer a condição: $A_i[1][0] < 10^{-10}$. Para tanto, lembre-se dos passos do algoritmo discutidos em aula:

Inicializando:
$$ A_0 = A $$

Em cada loop:
$$
A_0 = Q_0R_0 \\
A_1 = Q_0^T A_0 Q_0 \\
A_0 \leftarrow A_1 \\
$$

Para a decomposição QR, utilize o comando [`np.linalg.qr`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html).

Ao final do loop imprima os resultados:
$$
print(iter, A[1][0], A)
$$

iter = número de iterações necessárias para convergência.

In [3]:
# Insira seu código aqui
iter = 0
A0 = A
while A0[1][0] >= 10**(-10):
    Q0, R0 = np.linalg.qr(A0)
    A1 = Q0.T @ A0 @ Q0
    A0 = A1
    iter += 1

print('iter:', iter)
print('A[1][0]:', A0[1][0])
print('A:\n', A0)

iter: 8
A[1][0]: 5.732002112419967e-11
A:
 [[ 6.80926658e+02 -1.29785032e+02  4.80041164e+01 -3.29556298e+01
   1.68972534e+01]
 [ 5.73200211e-11  1.76584862e+01 -3.93993217e+00  3.88794875e+00
  -2.17967109e+00]
 [ 3.33982036e-19  2.81474339e-07  1.97306278e+00 -4.82611341e-01
   4.47583094e-01]
 [ 2.44362336e-25  4.39438347e-13  8.16740274e-06  4.12353531e-01
  -1.89839676e-01]
 [ 2.47951401e-35  1.02751450e-22  4.14388092e-15  4.76109443e-10
   2.94391956e-02]]


**1.1.2** Repita o exercício anterior, agora simplificando o algoritmo QR, considerando a relação:

$$ Q_0^TA_0 = R_0 $$

Ao final do loop imprima os resultados:

$$ print(iter, R_0, A[1][0], A) $$

iter = número de iterações necessárias para convergência.

In [4]:
# Insira seu código aqui
iter = 0
A0 = A
while A0[1][0] >= 10**(-10):
    Q0, R0 = np.linalg.qr(A0)
    A1 = R0 @ Q0
    A0 = A1
    iter += 1

print('iter:', iter)
print('R_0:\n', R0)
print('A[1][0]:', A0[1][0])
print('A:\n', A0)

iter: 8
R_0:
 [[-6.80926658e+02  1.29785039e+02 -4.80047507e+01  3.29546793e+01
   1.68972529e+01]
 [ 0.00000000e+00 -1.76584868e+01  3.94000666e+00 -3.88787075e+00
  -2.17967102e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.97307233e+00  4.82572268e-01
   4.47583086e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.12353534e-01
  -1.89839670e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.94391956e-02]]
A[1][0]: 5.732002112419974e-11
A:
 [[ 6.80926658e+02 -1.29785032e+02  4.80041164e+01 -3.29556298e+01
   1.68972534e+01]
 [ 5.73200211e-11  1.76584862e+01 -3.93993217e+00  3.88794875e+00
  -2.17967109e+00]
 [ 3.33982036e-19  2.81474339e-07  1.97306278e+00 -4.82611341e-01
   4.47583094e-01]
 [ 2.44362336e-25  4.39438347e-13  8.16740274e-06  4.12353531e-01
  -1.89839676e-01]
 [ 2.47951401e-35  1.02751450e-22  4.14388092e-15  4.76109443e-10
   2.94391956e-02]]


O próximo passo agora é utilizar o algoritmo QR para encontrar valores singulares de matrizes não quadradas. Considere para este exercício as matrizes B e C abaixo:

In [5]:
B = np.array([[4, 5, 6], [7, 8, 9]])
C = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [10, 10, 7, 2]])
print('B:', '\n', B)
print('C:', '\n', C)

B: 
 [[4 5 6]
 [7 8 9]]
C: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 10  7  2]]


**1.2.1** Para resolver essa questão, lembre-se que para qualquer matriz não quadrada B:

1. Existe uma decomposição $B = U \Sigma V^T$ 

1. $B^T B$ é quadrada, simétrica e admite decomposição espectral da forma: $B^T B = Q \Lambda Q^T$

3. Substituindo 1 em 2, temos: $B^T B = V \Sigma^2 V^T$

A nível de algoritmo, crie uma função generalista que retorna os valores singulares de qualquer matriz real, não quadrada seguindo os passos:

1. Calcule $S =B^T B$
2. Use o algoritmo QR para obter autovalores de $S$ (loop com 10 iterações).
3. Tire a raiz quadrada dos autovalores de S para obter os valores singulares de B.
4. Retorne um vetor **apenas com os valores singulares não nulos** (dica: [`np.diagonal`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html)).

Imprima a saída da sua função para B e C.

In [11]:
# Insira seu código aqui
def singValue(M):
    S = M.T @ M
    for i in range(10):
        [Q, R] = np.linalg.qr(S)
        S = R @ Q
    valores_singulares = np.sqrt(S.diagonal())
    index = np.argwhere(valores_singulares < 10**(-6))
    y = np.delete(valores_singulares, index)
    return y

singB = singValue(B)
print('singB:', singB)
singC = singValue(C)
print('singC:', singC)

singB: [16.45601991  0.44655204]
singC: [20.34572265  6.55272059  0.33678326]


### Questão 2 -Gauss-Jacobi e Gauss Seidel

Nesta seção, vamos implementar os algoritmos de Gauss-Jacobi e Gauss Seidel para resolver o sistema $Ax = b$, tal como foi descrito nas aulas.

Dica 1:

Passos iterativos do método Gauss-Jacobi para uma matriz 3x3:

Dado um valor inicial para x: $\vec{x}^{k = 0} = [1, 1, 1]$

Realize a iteração:

$x_1^{k+1} = (b_1 - a_{12} x_2^{(k)} - a_{13}x_3^{(k)})/a_{11}$

$x_2^{k+1} = (b_2 - a_{21} x_1^{(k)} - a_{23}x_3^{(k)})/a_{22}$

$x_3^{k+1} = (b_3 - a_{31} x_1^{(k)} - a_{32}x_2^{(k)})/a_{33}$

Dica 2:

Passos iterativos do método Gauss-Seidel para uma matriz 3x3:

Dado um valor inicial para x: $\vec{x}^{k = 0} = [1, 1, 1]$

Realize a iteração:

$x_1^{k+1} = (b_1 - a_{12} x_2^{(k)} - a_{13}x_3^{(k)})/a_{11}$

$x_2^{k+1} = (b_2 - a_{21} x_1^{(k+1)} - a_{23}x_3^{(k)})/a_{22}$

$x_3^{k+1} = (b_3 - a_{31} x_1^{(k+1)} - a_{32}x_2^{(k+1)})/a_{33}$

Dica 3:

Ao fazer o exercício no Colab tive problemas de arredondamento ao criar o vetor x_iter com o comando np.array. Caso tenham este problema, basta declarar x_iter como uma lista.

**2.1** Encontre a solução do sistema $Ax = b$, pelo método de Gauss-Jacobi realizando a iteração do método 5 vezes. A cada iteração, realize o print da sua estimativa para x. Neste exercício, considere a primeira estimativa de $x = [1, 1, 1]$, com A e b definidos abaixo.

Após rodar o algoritmo, faça um print da sua solução, comparando com a saída do método numpy: np.linalg.solve(A,b)

In [7]:
# ATENÇÃO: Não editar esta célula
A = np.array([[27, 6, -2], [6, 15, 2], [1, 1, 54]])
b = np.array([85, 72, 110])
print('A: \n', A)
print('b: \n', b)

A: 
 [[27  6 -2]
 [ 6 15  2]
 [ 1  1 54]]
b: 
 [ 85  72 110]


In [8]:
# Insira seu código aqui
x_old = np.array([1.0, 1.0, 1.0])
x_new = x_old.copy()
for i in range(5):
    x_new[0] = (85 - 6 * x_old[1] + 2 * x_old[2]) / 27
    x_new[1] = (72 - 6 * x_old[0] - 2 * x_old[2]) / 15
    x_new[2] = (110 - 1 * x_old[0] - 1 * x_old[1]) / 54
    print('iter:',i+1, 'x:', x_new)
    x_old = x_new.copy()

print('Numpy:', np.linalg.solve(A, b))

iter: 1 x: [3.         4.26666667 2.        ]
iter: 2 x: [2.34814815 3.33333333 1.90246914]
iter: 3 x: [2.54833105 3.60707819 1.93182442]
iter: 4 x: [2.48967332 3.52309099 1.92304798]
iter: 5 x: [2.50768704 3.54772427 1.92568955]
Numpy: [2.50366797 3.54185509 1.92508291]


**2.2** Repita o exercício anterior, agora pelo método de Gauss-Seidel

In [9]:
# Insira seu código aqui
x_iter = np.array([1.0, 1.0, 1.0])
for i in range(5):
    x_iter[0] = (85 - 6 * x_iter[1] + 2 * x_iter[2]) / 27
    x_iter[1] = (72 - 6 * x_iter[0] - 2 * x_iter[2]) / 15
    x_iter[2] = (110 - 1 * x_iter[0] - 1 * x_iter[1]) / 54
    print('iter:',i+1, 'x:', x_iter)

print('Numpy:', np.linalg.solve(A, b))

iter: 1 x: [3.         3.46666667 1.91728395]
iter: 2 x: [2.51979881 3.53644262 1.92488442]
iter: 3 x: [2.50485604 3.54140633 1.92506922]
iter: 4 x: [2.50376668 3.54181743 1.92508178]
iter: 5 x: [2.50367626 3.54185193 1.92508281]
Numpy: [2.50366797 3.54185509 1.92508291]
